# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bb/work/probe_basic-pyqt5-x86/sources/debian/python3-probe-basic/usr/share/configs/machine_setup_files/user_dro_display/xyza_dros/dros_xyza.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dros_xyza(object):
    def setupUi(self, dros_xyza):
        dros_xyza.setObjectName("dros_xyza")
        dros_xyza.resize(469, 272)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dros_xyza.sizePolicy().hasHeightForWidth())
        dros_xyza.setSizePolicy(sizePolicy)
        dros_xyza.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(dros_xyza)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgets_xyza = QtWidgets.QWidget(dros_xyza)
        self.widgets_xyza.setObjectName("widgets_xyza")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout(self.widgets_xyza)
        self.verticalLayout_56.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_56.setSpacing(4)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_77.setSpacing(8)
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.frame = QtWidgets.QFrame(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setStyleSheet(".QFrame{\n"
"    border-style: solid;\n"
"    border-color: rgb(176, 179,172);\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(90, 90, 90);\n"
"    padding: -5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_144 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_144.setContentsMargins(15, -1, 20, -1)
        self.horizontalLayout_144.setSpacing(8)
        self.horizontalLayout_144.setObjectName("horizontalLayout_144")
        self.axis_column_header = StatusLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axis_column_header.sizePolicy().hasHeightForWidth())
        self.axis_column_header.setSizePolicy(sizePolicy)
        self.axis_column_header.setMinimumSize(QtCore.QSize(60, 17))
        self.axis_column_header.setMaximumSize(QtCore.QSize(60, 17))
        self.axis_column_header.setStyleSheet("QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"    font: 16pt \"Bebas Kai\";\n"
"    padding-left: 1px;\n"
"    padding-right: 20px;\n"
"}")
        self.axis_column_header.setAlignment(QtCore.Qt.AlignCenter)
        self.axis_column_header.setObjectName("axis_column_header")
        self.horizontalLayout_144.addWidget(self.axis_column_header)
        self.work_column_header = StatusLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_column_header.sizePolicy().hasHeightForWidth())
        self.work_column_header.setSizePolicy(sizePolicy)
        self.work_column_header.setMinimumSize(QtCore.QSize(100, 17))
        self.work_column_header.setMaximumSize(QtCore.QSize(100, 17))
        self.work_column_header.setStyleSheet("QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"    font: 16pt \"Bebas Kai\";\n"
"    padding-left: 6px;\n"
"}")
        self.work_column_header.setAlignment(QtCore.Qt.AlignCenter)
        self.work_column_header.setObjectName("work_column_header")
        self.horizontalLayout_144.addWidget(self.work_column_header)
        self.machine_column_header = QtWidgets.QLabel(self.frame)
        self.machine_column_header.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.machine_column_header.sizePolicy().hasHeightForWidth())
        self.machine_column_header.setSizePolicy(sizePolicy)
        self.machine_column_header.setMinimumSize(QtCore.QSize(100, 17))
        self.machine_column_header.setMaximumSize(QtCore.QSize(100, 17))
        self.machine_column_header.setStyleSheet("QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"    font: 16pt \"Bebas Kai\";\n"
"}")
        self.machine_column_header.setAlignment(QtCore.Qt.AlignCenter)
        self.machine_column_header.setObjectName("machine_column_header")
        self.horizontalLayout_144.addWidget(self.machine_column_header)
        self.dtg_column_header = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtg_column_header.sizePolicy().hasHeightForWidth())
        self.dtg_column_header.setSizePolicy(sizePolicy)
        self.dtg_column_header.setMinimumSize(QtCore.QSize(100, 17))
        self.dtg_column_header.setMaximumSize(QtCore.QSize(100, 17))
        self.dtg_column_header.setStyleSheet("QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"    font: 16pt \"Bebas Kai\";\n"
"}")
        self.dtg_column_header.setAlignment(QtCore.Qt.AlignCenter)
        self.dtg_column_header.setObjectName("dtg_column_header")
        self.horizontalLayout_144.addWidget(self.dtg_column_header)
        self.ref_column_header = StatusLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_column_header.sizePolicy().hasHeightForWidth())
        self.ref_column_header.setSizePolicy(sizePolicy)
        self.ref_column_header.setMinimumSize(QtCore.QSize(40, 17))
        self.ref_column_header.setMaximumSize(QtCore.QSize(40, 17))
        self.ref_column_header.setStyleSheet("QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"    font: 16pt \"Bebas Kai\";\n"
"    padding-left: 6px;\n"
"}")
        self.ref_column_header.setAlignment(QtCore.Qt.AlignCenter)
        self.ref_column_header.setObjectName("ref_column_header")
        self.horizontalLayout_144.addWidget(self.ref_column_header)
        self.horizontalLayout_77.addWidget(self.frame)
        self.verticalLayout_56.addLayout(self.horizontalLayout_77)
        self.x_axis_dro_layout_3 = QtWidgets.QHBoxLayout()
        self.x_axis_dro_layout_3.setContentsMargins(1, 1, 1, 1)
        self.x_axis_dro_layout_3.setSpacing(7)
        self.x_axis_dro_layout_3.setObjectName("x_axis_dro_layout_3")
        self.zero_x_button = MDIButton(self.widgets_xyza)
        self.zero_x_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_x_button.sizePolicy().hasHeightForWidth())
        self.zero_x_button.setSizePolicy(sizePolicy)
        self.zero_x_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_x_button.setMaximumSize(QtCore.QSize(60, 40))
        self.zero_x_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero_x_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zero_x_button.setStyleSheet("MDIButton {\n"
"       font: 17pt \"Bebas Kai\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/zero.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zero_x_button.setIcon(icon)
        self.zero_x_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_x_button.setObjectName("zero_x_button")
        self.x_axis_dro_layout_3.addWidget(self.zero_x_button)
        self.drowidget_x = DROLineEdit(self.widgets_xyza)
        self.drowidget_x.setMinimumSize(QtCore.QSize(100, 35))
        self.drowidget_x.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bebas Kai")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.drowidget_x.setFont(font)
        self.drowidget_x.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.drowidget_x.setStyleSheet("QLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.drowidget_x.setCursorPosition(10)
        self.drowidget_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drowidget_x.setProperty("referenceType", 1)
        self.drowidget_x.setProperty("axisNumber", 0)
        self.drowidget_x.setProperty("latheMode", 0)
        self.drowidget_x.setObjectName("drowidget_x")
        self.x_axis_dro_layout_3.addWidget(self.drowidget_x)
        self.drolabel_machine_x = DROLabel(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_machine_x.sizePolicy().hasHeightForWidth())
        self.drolabel_machine_x.setSizePolicy(sizePolicy)
        self.drolabel_machine_x.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_x.setMaximumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_x.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_machine_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_machine_x.setProperty("referenceType", 0)
        self.drolabel_machine_x.setProperty("axisNumber", 0)
        self.drolabel_machine_x.setProperty("latheMode", 0)
        self.drolabel_machine_x.setObjectName("drolabel_machine_x")
        self.x_axis_dro_layout_3.addWidget(self.drolabel_machine_x)
        self.drolabel_dtg_x = DROLabel(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_dtg_x.sizePolicy().hasHeightForWidth())
        self.drolabel_dtg_x.setSizePolicy(sizePolicy)
        self.drolabel_dtg_x.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_dtg_x.setMaximumSize(QtCore.QSize(100, 35))
        self.drolabel_dtg_x.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}")
        self.drolabel_dtg_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_dtg_x.setProperty("referenceType", 2)
        self.drolabel_dtg_x.setProperty("axisNumber", 0)
        self.drolabel_dtg_x.setProperty("latheMode", 0)
        self.drolabel_dtg_x.setObjectName("drolabel_dtg_x")
        self.x_axis_dro_layout_3.addWidget(self.drolabel_dtg_x)
        self.ref_x_button = ActionButton(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_x_button.sizePolicy().hasHeightForWidth())
        self.ref_x_button.setSizePolicy(sizePolicy)
        self.ref_x_button.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_x_button.setMaximumSize(QtCore.QSize(62, 40))
        self.ref_x_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_x_button.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_x_button.setObjectName("ref_x_button")
        self.x_axis_dro_layout_3.addWidget(self.ref_x_button)
        self.verticalLayout_56.addLayout(self.x_axis_dro_layout_3)
        self.y_axis_dro_layout_3 = QtWidgets.QHBoxLayout()
        self.y_axis_dro_layout_3.setContentsMargins(1, 1, 1, 1)
        self.y_axis_dro_layout_3.setSpacing(7)
        self.y_axis_dro_layout_3.setObjectName("y_axis_dro_layout_3")
        self.zero_y_button = MDIButton(self.widgets_xyza)
        self.zero_y_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_y_button.sizePolicy().hasHeightForWidth())
        self.zero_y_button.setSizePolicy(sizePolicy)
        self.zero_y_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_y_button.setMaximumSize(QtCore.QSize(60, 40))
        self.zero_y_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero_y_button.setStyleSheet("MDIButton {\n"
"       font: 17pt \"Bebas Kai\";\n"
"}")
        self.zero_y_button.setIcon(icon)
        self.zero_y_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_y_button.setObjectName("zero_y_button")
        self.y_axis_dro_layout_3.addWidget(self.zero_y_button)
        self.drowidget_y = DROLineEdit(self.widgets_xyza)
        self.drowidget_y.setMinimumSize(QtCore.QSize(100, 35))
        self.drowidget_y.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bebas Kai")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.drowidget_y.setFont(font)
        self.drowidget_y.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.drowidget_y.setStyleSheet("QLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.drowidget_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drowidget_y.setProperty("axisNumber", 1)
        self.drowidget_y.setObjectName("drowidget_y")
        self.y_axis_dro_layout_3.addWidget(self.drowidget_y)
        self.drolabel_machine_y = DROLabel(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_machine_y.sizePolicy().hasHeightForWidth())
        self.drolabel_machine_y.setSizePolicy(sizePolicy)
        self.drolabel_machine_y.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_y.setMaximumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_y.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_machine_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_machine_y.setProperty("referenceType", 0)
        self.drolabel_machine_y.setProperty("axisNumber", 1)
        self.drolabel_machine_y.setProperty("latheMode", 0)
        self.drolabel_machine_y.setObjectName("drolabel_machine_y")
        self.y_axis_dro_layout_3.addWidget(self.drolabel_machine_y)
        self.drolabel_dtg_y = DROLabel(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_dtg_y.sizePolicy().hasHeightForWidth())
        self.drolabel_dtg_y.setSizePolicy(sizePolicy)
        self.drolabel_dtg_y.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_dtg_y.setMaximumSize(QtCore.QSize(100, 35))
        self.drolabel_dtg_y.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}")
        self.drolabel_dtg_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_dtg_y.setProperty("referenceType", 2)
        self.drolabel_dtg_y.setProperty("axisNumber", 1)
        self.drolabel_dtg_y.setProperty("latheMode", 0)
        self.drolabel_dtg_y.setObjectName("drolabel_dtg_y")
        self.y_axis_dro_layout_3.addWidget(self.drolabel_dtg_y)
        self.ref_y_button = ActionButton(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_y_button.sizePolicy().hasHeightForWidth())
        self.ref_y_button.setSizePolicy(sizePolicy)
        self.ref_y_button.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_y_button.setMaximumSize(QtCore.QSize(62, 40))
        self.ref_y_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_y_button.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_y_button.setObjectName("ref_y_button")
        self.y_axis_dro_layout_3.addWidget(self.ref_y_button)
        self.verticalLayout_56.addLayout(self.y_axis_dro_layout_3)
        self.z_axis_dro_layout_3 = QtWidgets.QHBoxLayout()
        self.z_axis_dro_layout_3.setContentsMargins(1, 1, 1, 1)
        self.z_axis_dro_layout_3.setSpacing(7)
        self.z_axis_dro_layout_3.setObjectName("z_axis_dro_layout_3")
        self.zero_z_button = MDIButton(self.widgets_xyza)
        self.zero_z_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_z_button.sizePolicy().hasHeightForWidth())
        self.zero_z_button.setSizePolicy(sizePolicy)
        self.zero_z_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_z_button.setMaximumSize(QtCore.QSize(60, 40))
        self.zero_z_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero_z_button.setStyleSheet("MDIButton {\n"
"       font: 17pt \"Bebas Kai\";\n"
"}")
        self.zero_z_button.setIcon(icon)
        self.zero_z_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_z_button.setObjectName("zero_z_button")
        self.z_axis_dro_layout_3.addWidget(self.zero_z_button)
        self.drowidget_z = DROLineEdit(self.widgets_xyza)
        self.drowidget_z.setMinimumSize(QtCore.QSize(100, 35))
        self.drowidget_z.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bebas Kai")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.drowidget_z.setFont(font)
        self.drowidget_z.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.drowidget_z.setStyleSheet("QLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.drowidget_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drowidget_z.setProperty("axisNumber", 2)
        self.drowidget_z.setObjectName("drowidget_z")
        self.z_axis_dro_layout_3.addWidget(self.drowidget_z)
        self.drolabel_machine_z = DROLabel(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_machine_z.sizePolicy().hasHeightForWidth())
        self.drolabel_machine_z.setSizePolicy(sizePolicy)
        self.drolabel_machine_z.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_z.setMaximumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_z.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_machine_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_machine_z.setProperty("referenceType", 0)
        self.drolabel_machine_z.setProperty("axisNumber", 2)
        self.drolabel_machine_z.setProperty("latheMode", 0)
        self.drolabel_machine_z.setObjectName("drolabel_machine_z")
        self.z_axis_dro_layout_3.addWidget(self.drolabel_machine_z)
        self.drolabel_dtg_z = DROLabel(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_dtg_z.sizePolicy().hasHeightForWidth())
        self.drolabel_dtg_z.setSizePolicy(sizePolicy)
        self.drolabel_dtg_z.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_dtg_z.setMaximumSize(QtCore.QSize(100, 35))
        self.drolabel_dtg_z.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}")
        self.drolabel_dtg_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_dtg_z.setProperty("referenceType", 2)
        self.drolabel_dtg_z.setProperty("axisNumber", 2)
        self.drolabel_dtg_z.setProperty("latheMode", 0)
        self.drolabel_dtg_z.setObjectName("drolabel_dtg_z")
        self.z_axis_dro_layout_3.addWidget(self.drolabel_dtg_z)
        self.ref_z_button = ActionButton(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_z_button.sizePolicy().hasHeightForWidth())
        self.ref_z_button.setSizePolicy(sizePolicy)
        self.ref_z_button.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_z_button.setMaximumSize(QtCore.QSize(62, 40))
        self.ref_z_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_z_button.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_z_button.setObjectName("ref_z_button")
        self.z_axis_dro_layout_3.addWidget(self.ref_z_button)
        self.verticalLayout_56.addLayout(self.z_axis_dro_layout_3)
        self.a_axis_dro_layout_2 = QtWidgets.QHBoxLayout()
        self.a_axis_dro_layout_2.setContentsMargins(1, 1, 1, 1)
        self.a_axis_dro_layout_2.setSpacing(7)
        self.a_axis_dro_layout_2.setObjectName("a_axis_dro_layout_2")
        self.zero_a_button = MDIButton(self.widgets_xyza)
        self.zero_a_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_a_button.sizePolicy().hasHeightForWidth())
        self.zero_a_button.setSizePolicy(sizePolicy)
        self.zero_a_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_a_button.setMaximumSize(QtCore.QSize(60, 40))
        self.zero_a_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero_a_button.setStyleSheet("MDIButton {\n"
"       font: 17pt \"Bebas Kai\";\n"
"}")
        self.zero_a_button.setIcon(icon)
        self.zero_a_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_a_button.setObjectName("zero_a_button")
        self.a_axis_dro_layout_2.addWidget(self.zero_a_button)
        self.drowidget_a = DROLineEdit(self.widgets_xyza)
        self.drowidget_a.setMinimumSize(QtCore.QSize(100, 35))
        self.drowidget_a.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Bebas Kai")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.drowidget_a.setFont(font)
        self.drowidget_a.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.drowidget_a.setStyleSheet("QLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.drowidget_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drowidget_a.setProperty("axisNumber", 3)
        self.drowidget_a.setObjectName("drowidget_a")
        self.a_axis_dro_layout_2.addWidget(self.drowidget_a)
        self.drolabel_machine_a = DROLabel(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_machine_a.sizePolicy().hasHeightForWidth())
        self.drolabel_machine_a.setSizePolicy(sizePolicy)
        self.drolabel_machine_a.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_a.setMaximumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_a.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_machine_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_machine_a.setProperty("referenceType", 0)
        self.drolabel_machine_a.setProperty("axisNumber", 3)
        self.drolabel_machine_a.setProperty("latheMode", 0)
        self.drolabel_machine_a.setObjectName("drolabel_machine_a")
        self.a_axis_dro_layout_2.addWidget(self.drolabel_machine_a)
        self.drolabel_dtg_a = DROLabel(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_dtg_a.sizePolicy().hasHeightForWidth())
        self.drolabel_dtg_a.setSizePolicy(sizePolicy)
        self.drolabel_dtg_a.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_dtg_a.setMaximumSize(QtCore.QSize(100, 35))
        self.drolabel_dtg_a.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}")
        self.drolabel_dtg_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_dtg_a.setProperty("referenceType", 2)
        self.drolabel_dtg_a.setProperty("axisNumber", 3)
        self.drolabel_dtg_a.setProperty("latheMode", 0)
        self.drolabel_dtg_a.setObjectName("drolabel_dtg_a")
        self.a_axis_dro_layout_2.addWidget(self.drolabel_dtg_a)
        self.ref_a_button = ActionButton(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_a_button.sizePolicy().hasHeightForWidth())
        self.ref_a_button.setSizePolicy(sizePolicy)
        self.ref_a_button.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_a_button.setMaximumSize(QtCore.QSize(62, 40))
        self.ref_a_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_a_button.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_a_button.setObjectName("ref_a_button")
        self.a_axis_dro_layout_2.addWidget(self.ref_a_button)
        self.verticalLayout_56.addLayout(self.a_axis_dro_layout_2)
        self.horizontalLayout_104 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_104.setContentsMargins(3, 1, 3, 1)
        self.horizontalLayout_104.setSpacing(20)
        self.horizontalLayout_104.setObjectName("horizontalLayout_104")
        self.zero_all_button = MDIButton(self.widgets_xyza)
        self.zero_all_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_all_button.sizePolicy().hasHeightForWidth())
        self.zero_all_button.setSizePolicy(sizePolicy)
        self.zero_all_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_all_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.zero_all_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero_all_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zero_all_button.setStyleSheet("MDIButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.zero_all_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_all_button.setObjectName("zero_all_button")
        self.horizontalLayout_104.addWidget(self.zero_all_button)
        self.ref_all_button = ActionButton(self.widgets_xyza)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_all_button.sizePolicy().hasHeightForWidth())
        self.ref_all_button.setSizePolicy(sizePolicy)
        self.ref_all_button.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_all_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ref_all_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_all_button.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_all_button.setObjectName("ref_all_button")
        self.horizontalLayout_104.addWidget(self.ref_all_button)
        self.verticalLayout_56.addLayout(self.horizontalLayout_104)
        self.verticalLayout.addWidget(self.widgets_xyza)

        self.retranslateUi(dros_xyza)
        QtCore.QMetaObject.connectSlotsByName(dros_xyza)

    def retranslateUi(self, dros_xyza):
        _translate = QtCore.QCoreApplication.translate
        dros_xyza.setWindowTitle(_translate("dros_xyza", "dros_xyza"))
        self.axis_column_header.setText(_translate("dros_xyza", "AXIS"))
        self.axis_column_header.setProperty("rules", _translate("dros_xyza", "[]"))
        self.work_column_header.setProperty("rules", _translate("dros_xyza", "[{\"channels\": [{\"url\": \"status:g5x_index?text\", \"trigger\": true}], \"property\": \"Text\", \"expression\": \"ch[0] + \' WORK\'\\n\", \"name\": \"WCS Header\"}]"))
        self.machine_column_header.setText(_translate("dros_xyza", "MACHINE"))
        self.dtg_column_header.setText(_translate("dros_xyza", "DTG"))
        self.ref_column_header.setText(_translate("dros_xyza", "REF"))
        self.ref_column_header.setProperty("rules", _translate("dros_xyza", "[]"))
        self.zero_x_button.setText(_translate("dros_xyza", "X"))
        self.zero_x_button.setProperty("rules", _translate("dros_xyza", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_x_button.setProperty("MDICommand", _translate("dros_xyza", "G10 L20 P{ch[0]} X0.0"))
        self.drowidget_x.setText(_translate("dros_xyza", "     0.000"))
        self.drowidget_x.setProperty("inchFormat", _translate("dros_xyza", "%9.4f"))
        self.drowidget_x.setProperty("millimeterFormat", _translate("dros_xyza", "%10.3f"))
        self.drowidget_x.setProperty("degreeFormat", _translate("dros_xyza", "%10.2f"))
        self.drolabel_machine_x.setProperty("inchFormat", _translate("dros_xyza", "%9.4f"))
        self.drolabel_machine_x.setProperty("millimeterFormat", _translate("dros_xyza", "%10.3f"))
        self.drolabel_machine_x.setProperty("degreeFormat", _translate("dros_xyza", "%10.2f"))
        self.drolabel_dtg_x.setProperty("inchFormat", _translate("dros_xyza", "%9.4f"))
        self.drolabel_dtg_x.setProperty("millimeterFormat", _translate("dros_xyza", "%10.3f"))
        self.drolabel_dtg_x.setProperty("degreeFormat", _translate("dros_xyza", "%10.2f"))
        self.ref_x_button.setText(_translate("dros_xyza", "REF X"))
        self.ref_x_button.setProperty("rules", _translate("dros_xyza", "[{\"name\": \"home_prohibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_x_button.setProperty("actionName", _translate("dros_xyza", "machine.home.axis:x"))
        self.zero_y_button.setText(_translate("dros_xyza", "Y"))
        self.zero_y_button.setProperty("rules", _translate("dros_xyza", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_y_button.setProperty("MDICommand", _translate("dros_xyza", "G10 L20 P{ch[0]} Y0.0"))
        self.drolabel_machine_y.setProperty("inchFormat", _translate("dros_xyza", "%9.4f"))
        self.drolabel_machine_y.setProperty("millimeterFormat", _translate("dros_xyza", "%10.3f"))
        self.drolabel_machine_y.setProperty("degreeFormat", _translate("dros_xyza", "%10.2f"))
        self.drolabel_dtg_y.setProperty("inchFormat", _translate("dros_xyza", "%9.4f"))
        self.drolabel_dtg_y.setProperty("millimeterFormat", _translate("dros_xyza", "%10.3f"))
        self.drolabel_dtg_y.setProperty("degreeFormat", _translate("dros_xyza", "%10.2f"))
        self.ref_y_button.setText(_translate("dros_xyza", "REF Y"))
        self.ref_y_button.setProperty("rules", _translate("dros_xyza", "[{\"name\": \"home_prohibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_y_button.setProperty("actionName", _translate("dros_xyza", "machine.home.axis:y"))
        self.zero_z_button.setText(_translate("dros_xyza", "Z"))
        self.zero_z_button.setProperty("rules", _translate("dros_xyza", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_z_button.setProperty("MDICommand", _translate("dros_xyza", "G10 L20 P{ch[0]} Z0.0"))
        self.drolabel_machine_z.setProperty("inchFormat", _translate("dros_xyza", "%9.4f"))
        self.drolabel_machine_z.setProperty("millimeterFormat", _translate("dros_xyza", "%10.3f"))
        self.drolabel_machine_z.setProperty("degreeFormat", _translate("dros_xyza", "%10.2f"))
        self.drolabel_dtg_z.setProperty("inchFormat", _translate("dros_xyza", "%9.4f"))
        self.drolabel_dtg_z.setProperty("millimeterFormat", _translate("dros_xyza", "%10.3f"))
        self.drolabel_dtg_z.setProperty("degreeFormat", _translate("dros_xyza", "%10.2f"))
        self.ref_z_button.setText(_translate("dros_xyza", "REF Z"))
        self.ref_z_button.setProperty("rules", _translate("dros_xyza", "[{\"name\": \"home_prohibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_z_button.setProperty("actionName", _translate("dros_xyza", "machine.home.axis:z"))
        self.zero_a_button.setText(_translate("dros_xyza", "A"))
        self.zero_a_button.setProperty("rules", _translate("dros_xyza", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_a_button.setProperty("MDICommand", _translate("dros_xyza", "G10 L20 P{ch[0]} A0.0"))
        self.drolabel_machine_a.setProperty("inchFormat", _translate("dros_xyza", "%9.4f"))
        self.drolabel_machine_a.setProperty("millimeterFormat", _translate("dros_xyza", "%10.3f"))
        self.drolabel_machine_a.setProperty("degreeFormat", _translate("dros_xyza", "%10.2f"))
        self.drolabel_dtg_a.setProperty("inchFormat", _translate("dros_xyza", "%9.4f"))
        self.drolabel_dtg_a.setProperty("millimeterFormat", _translate("dros_xyza", "%10.3f"))
        self.drolabel_dtg_a.setProperty("degreeFormat", _translate("dros_xyza", "%10.2f"))
        self.ref_a_button.setText(_translate("dros_xyza", "REF A"))
        self.ref_a_button.setProperty("rules", _translate("dros_xyza", "[{\"name\": \"home_prohibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_a_button.setProperty("actionName", _translate("dros_xyza", "machine.home.axis:a"))
        self.zero_all_button.setText(_translate("dros_xyza", "ZERO ALL"))
        self.zero_all_button.setProperty("rules", _translate("dros_xyza", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_all_button.setProperty("MDICommand", _translate("dros_xyza", "G10 L20 P{ch[0]} X0.0 Y0.0 Z0.0"))
        self.ref_all_button.setText(_translate("dros_xyza", "REF ALL"))
        self.ref_all_button.setProperty("rules", _translate("dros_xyza", "[{\"channels\": [{\"url\": \"status:all_axes_homed\", \"trigger\": true}], \"property\": \"Text\", \"expression\": \"\'HOMED\' if ch[0] else \'REF ALL\'\", \"name\": \"reference_all\"}, {\"name\": \"home_prohibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_all_button.setProperty("actionName", _translate("dros_xyza", "machine.home.all"))
from qtpyvcp.widgets.button_widgets.action_button import ActionButton
from qtpyvcp.widgets.button_widgets.mdi_button import MDIButton
from qtpyvcp.widgets.display_widgets.dro_label import DROLabel
from qtpyvcp.widgets.display_widgets.status_label import StatusLabel
from qtpyvcp.widgets.input_widgets.dro_line_edit import DROLineEdit
import probe_basic_rc
